services:
    csgo-server:
        build: .
        ports:
            - "8080:80"
            - "443:443"
            - "8545:8545"
            - "8546:8546"
            - "30303:30303"

volumes:
    data:
        mountPoint: "/csgo"